### ISSUE TITLE
How to publish for organization

### ISSUE THREAD

**Issue by mdeuerlein** [BoostIO/Boostlog-feedback#1]
I just created an organization. But I am wondering how to publish a post as organization?

**Comment by Rokt33r** [comment]
<img width="771" alt="screen shot 2018-02-26 at 9 25 33 pm" src="https://user-images.githubusercontent.com/5865853/36670427-a32f496c-1b3b-11e8-9c7f-817550f5b3c4.png">

You can do it with this select element!

**Comment by mdeuerlein** [comment]
@Rokt33r Nope. There is only my name to choose in the dropdown.

**Comment by Rokt33r** [comment]
We removed organization stuff temporary. It might come back when the app becomes popular.
